# Generated by Django 4.1.5 on 2023-01-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1024)),
                ('is_done', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
